### ISSUE TITLE
Peer-to-Peer code review Stand-Up meeting

### ISSUE THREAD

**Issue by srueda27** [srueda27/NYT-Clone#1]

**Comment by simondebbarma** [comment]
# Keep it up! You're almost there.
---

My suggestions :

- Set a fixed width to your **main** tag. I would suggest 1440px. It will fix a lot of issues.
- Put your image caption in a **div** along with the **img** as a sibling of the caption.
- Image positioning for the infograph with text overlay, needs to be improved. Set a fixed-width for parent div with position relative. Inside that, have your images and text divs. Put your image as a cover and put **absolute** positions for your text divs.
- I'm not sure using empty divs in your footer links is necessary. Using a clear for the following element (bottom navbar) would be great.

---

<img src="https://media.giphy.com/media/5PhvV8Q5zV0EXIZ5mD/giphy.gif" width="100%">

**Comment by EdCrux** [comment]
Great Job!
To improve your webpage:
 - Center your article title.
 - I watched your page on a 1080hd  screen and some elements go to the left.
 - Place the asides suggestions near of the main text.

Good Look!

**Comment by dxania** [comment]
Good work so far. Ensure to cater for bigger screen sizes

**Comment by srueda27** [comment]
We took care of the issues, thank you for the reviews
